[extension]
name = "temporal_tables"
version = "1.2.2"
repository = "https://github.com/arkhipov/temporal_tables"
license = "BSD-2-Clause"
description = "Temporal Tables PostgreSQL Extension."
documentation = "https://github.com/arkhipov/temporal_tables"
categories = ["auditing_logging"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C temporal_tables install"
