[extension]
name = "pg_hint_plan15"
version = "1.4.3"
repository = "https://github.com/ossc-db/pg_hint_plan"
license = "Copyright"
description = "pg_hint_plan makes it possible to tweak PostgreSQL execution plans."
homepage = "http://www.oss.ecl.ntt.co.jp/ossc/"
documentation = "https://github.com/ossc-db/pg_hint_plan"
categories = ["query_optimizations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "14"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pg_hint_plan install"
