[extension]
name = "pg_extra_time"
version = "1.1.2"
repository = "https://github.com/bigsmoke/pg_extra_time"
license = "PostgreSQL"
description = "Additional date time functions."
categories = ["data_transformations"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
