[extension]
name = "multicorn"
version = "3.0.0"
repository = "https://github.com/pgsql-io/multicorn2"
license = "PostgreSQL"
description = "Multicorn is a PostgreSQL extension that allows you to create foreign data wrappers in Python."
homepage = "https://github.com/pgsql-io/multicorn2"
documentation = "https://github.com/pgsql-io/multicorn2/blob/main/README.md"
categories = ["connectors"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C multicorn install"