[extension]
name = "lower_quantile"
version = "1.0.0"
repository = "https://github.com/tvondra/lower_quantile"
license = "BSD-2-Clause"
description = "Provides lower_quantile aggregate function."
documentation = "https://github.com/tvondra/lower_quantile"
categories = ["analytics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C lower_quantile install"
