[extension]
name = "timescaledb"
version = "2.17.2"
repository = "https://github.com/timescale/timescaledb"
license = "Apache-2.0"
description = "An open-source time-series SQL database optimized for fast ingest and complex queries. Packaged as a PostgreSQL extension."
homepage = "https://www.timescale.com/"
documentation = "https://docs.timescale.com/"
categories = ["analytics"]
loadable_libraries = [{ library_name = "timescaledb", requires_restart = true }]

[dependencies]
apt = ["libssl3", "openssl", "libpq5", "libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C timescaledb/build install"
