[extension]
name = "sslutils"
version = "1.4.0"
repository = "https://github.com/EnterpriseDB/sslutils"
license = "PostgreSQL"
description = "A Postgres extension for managing SSL certificates through SQL."
homepage = "https://www.enterprisedb.com/"
documentation = "https://github.com/EnterpriseDB/sslutils"
categories = ["security"]

[dependencies]
apt = ["libssl3", "openssl", "libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C sslutils install"
