[extension]
name = "pg_similarity"
version = "1.0.0"
repository = "https://github.com/eulerto/pg_similarity"
license = "BSD-3-Clause"
description = "Support similarity queries."
documentation = "https://github.com/eulerto/pg_similarity"
categories = ["search"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pg_similarity USE_PGXS=1 install"
