[extension]
name = "random"
version = "1.0.0"
repository = "https://github.com/tvondra/random"
license = "PostgreSQL"
description = "Random data generator extension."
documentation = "https://github.com/tvondra/random"
categories = ["analytics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C random install"
