[extension]
name = "smlar"
version = "1.0.0"
repository = "https://github.com/jirutka/smlar/"
license = "PostgreSQL"
description = "PostgreSQL extension for an effective similarity search"
documentation = "https://github.com/jirutka/smlar/"
categories = ["search"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C smlar USE_PGXS=1 install"
