[extension]
name = "icu_ext"
version = "1.9.0"
repository = "https://github.com/dverite/icu_ext"
license = "PostgreSQL"
description = "Access ICU functions."
categories = ["data_transformations"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C icu_ext install"
