[extension]
name = "postgresql_topn"
version = "2.7.0"
repository = "https://github.com/citusdata/postgresql-topn"
license = "AGPL-3.0"
description = "TopN is an open source PostgreSQL extension that returns the top values in a database according to some criteria."
homepage = "https://www.citusdata.com/"
documentation = "https://github.com/citusdata/postgresql-topn"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C postgresql_topn install"
