[extension]
name = "rum"
version = "1.3.14"
repository = "https://github.com/postgrespro/rum"
license = "PostgreSQL"
description = "The rum module provides an access method to work with a RUM index."
homepage = "https://postgrespro.com/"
documentation = "https://postgrespro.com/docs/enterprise/13/rum"
categories = ["index_table_optimizations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C rum USE_PGXS=1 install"
