[extension]
name = "postgresql_hll"
version = "2.18.0"
repository = "https://github.com/citusdata/postgresql-hll"
license = "Apache-2.0"
description = "HyperLogLog data structures as a native data type."
homepage = "https://www.citusdata.com/"
documentation = "https://github.com/citusdata/postgresql-hll"
categories = ["analytics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C postgresql_hll install"
