[extension]
name = "jdbc_fdw"
version = "1.2.0"
repository = "https://github.com/pgspider/jdbc_fdw"
license = "PostgreSQL"
description = "PostgreSQL Foreign Data Wrapper for JDBC."
documentation = "https://github.com/pgspider/jdbc_fdw"
categories = ["connectors"]

[dependencies]
apt = ["libpq5", "libc6", "openjdk-18-jre-headless"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C jdbc_fdw install USE_PGXS=1"
