[extension]
name = "postgresql_anonymizer"
version = "1.3.2"
repository = "https://gitlab.com/dalibo/postgresql_anonymizer"
license = "PostgreSQL"
description = "Anonymization & Data Masking for PostgreSQL."
documentation = "https://gitlab.com/dalibo/postgresql_anonymizer"
categories = ["security"]
loadable_libraries = [{ library_name = "anon", requires_restart = true }]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C postgresql_anonymizer install"
