[extension]
name = "pg_semver"
version = "0.40.0"
repository = "https://github.com/theory/pg-semver"
license = "PostgreSQL"
description = "A semantic version data type for PostgreSQL."
documentation = "https://github.com/theory/pg-semver"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
