[extension]
name = "prefix"
version = "1.2.9"
repository = "https://github.com/dimitri/prefix"
license = "PostgreSQL"
description = "Prefix Range module for PostgreSQL."
documentation = "https://github.com/dimitri/prefix"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C prefix install"
