[extension]
name = "tembo_ivm"
version = "1.9.1"
repository = "https://github.com/tembo-io/pg_ivm"
license = "PostgreSQL"
description = "IVM (Incremental View Maintenance) implementation with Partitioned Support"
homepage = "https://www.sraoss.co.jp/index_en/"
documentation = "https://github.com/tembo-io/pg_ivm"
categories = ["change_data_capture"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C tembo_ivm install"
