[extension]
name = "zson"
version = "1.1.0"
repository = "https://github.com/postgrespro/zson"
license = "PostgreSQL"
description = "An extension for transparent JSONB compression"
homepage = "https://github.com/postgrespro/zson"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C zson install"
