[extension]
name = "supautils"
version = "2.6.0"
repository = "https://github.com/supabase/supautils"
license = "Apache-2.0"
description = "PostgreSQL extension that prevents doing ALTER/DROP/GRANT on a set of reserved roles."
homepage = "https://supabase.com/"
documentation = "https://supabase.github.io/supautils/"
categories = ["tooling_admin"]
preload_libraries = ["supautils"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C supautils install"
