[extension]
name = "tds_fdw"
version = "2.0.4"
repository = "https://github.com/tds-fdw/tds_fdw"
license = "Copyright"
description = "A PostgreSQL foreign data wrapper to connect to TDS databases (Sybase and Microsoft SQL Server)."
documentation = "https://github.com/tds-fdw/tds_fdw"
categories = ["connectors"]

[dependencies]
apt = ["libsybdb5", "libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C tds_fdw USE_PGXS=1 install"
