[extension]
name = "wal2json"
version = "2.6.0"
repository = "https://github.com/eulerto/wal2json"
license = "BSD-3-Clause"
description = "wal2json is an output plugin for logical decoding."
categories = ["change_data_capture"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C wal2json install"
