[extension]
name = "pg_savior"
version = "1.0.0"
repository = "https://github.com/viggy28/pg_savior"
license = ""
description = "pg_savior is a PostgreSQL extension designed to prevent accidental data loss due to non-parameterized DELETE queries without a WHERE clause."
homepage = "https://github.com/viggy28/pg_savior"
documentation = "https://github.com/viggy28/pg_savior"
categories = ["security"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pg_savior install"
