[extension]
name = "pgq"
version = "3.5.1"
repository = "https://github.com/pgq/pgq"
license = "ISC"
description = "Generic Queue for PostgreSQL."
documentation = "https://github.com/pgq/pgq"
categories = ["orchestration"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pgq install"
