[extension]
name = "postgresbson"
version = "2.0.2"
repository = "https://github.com/buzzm/postgresbson"
license = "MIT"
description = "This PostgreSQL extension realizes the BSON data type, together with functions to create and inspect BSON objects for the purposes of expressive and performant querying."
homepage = "https://github.com/buzzm/postgresbson"
documentation = "https://github.com/buzzm/postgresbson"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
