[extension]
name = "postgresql_logfdw"
version = "1.4.0"
repository = "https://github.com/aws/postgresql-logfdw"
license = "Apache-2.0"
description = "Foreign-data wrapper for Postgres log file access."
documentation = "https://github.com/aws/postgresql-logfdw"
categories = ["connectors"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C postgresql_logfdw USE_PGXS=1 install"
