[extension]
name = "oracle_fdw"
version = "1.2.0"
repository = "https://github.com/laurenz/oracle_fdw"
license = "Copyright"
description = "PostgreSQL Foreign Data Wrapper for Oracle."
documentation = "https://github.com/laurenz/oracle_fdw"
categories = ["connectors"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C oracle_fdw install USE_PGXS=1"
