[extension]
name = "pg_bigm"
version = "1.2.0"
repository = "https://github.com/pgbigm/pg_bigm"
license = "PostgreSQL"
description = "This module allows a user to create 2-gram (bigram) index for faster full text search."
homepage = "https://pgbigm.osdn.jp/index_en.html"
documentation = "https://pgbigm.osdn.jp/index_en.html#document"
categories = ["index_table_optimizations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pg_bigm USE_PGXS=1 install"
