[extension]
name = "pg_uuidv7"
version = "1.6.0"
repository = "https://github.com/fboulnois/pg_uuidv7"
license = "MPL-2.0"
description = "Create valid version 7 UUIDs in Postgres."
documentation = "https://github.com/fboulnois/pg_uuidv7"
categories = ["data_transformations"]
preload_libraries = ["pg_uuidv7"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
