[extension]
name = "pointcloud"
version = "1.2.5"
repository = "https://github.com/pgpointcloud/pointcloud/"
license = "Copyright"
description = "A PostgreSQL extension for storing point cloud (LIDAR) data."
documentation = "https://pgpointcloud.github.io/pointcloud/"
categories = ["data_transformations"]
preload_libraries = ["postgis"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pointcloud install"
