[extension]
name = "set_user"
version = "4.1.0"
repository = "https://github.com/pgaudit/set_user"
license = "PostgreSQL"
description = "PostgreSQL extension allowing privilege escalation with enhanced logging and control."
homepage = "https://www.pgaudit.org/"
documentation = "https://github.com/pgaudit/set_user"
categories = ["tooling_admin"]
preload_libraries = ["set_user"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C set_user install"
