[extension]
name = "pgsodium"
version = "3.1.9"
repository = "https://github.com/michelp/pgsodium"
license = "Copyright"
description = "Modern cryptography for PostgreSQL using libsodium."
documentation = "https://github.com/michelp/pgsodium"
categories = ["security"]

[dependencies]
apt = ["libsodium23", "libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pgsodium install"
