[extension]
name = "pgtap"
version = "1.3.3"
repository = "https://github.com/theory/pgtap"
license = "Copyright"
description = "Unit testing for PostgreSQL."
homepage = "https://pgtap.org/"
documentation = "https://pgtap.org/documentation.html"
categories = ["tooling_admin"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
