[extension]
name = "plrust"
version = "1.2.8"
repository = "https://github.com/tcdi/plrust"
license = "PostgreSQL"
description = "A Rust procedural language handler for PostgreSQL."
homepage = "https://www.tcdi.com/"
documentation = "https://tcdi.github.io/plrust/"
categories = ["procedural_languages"]
preload_libraries = ["plrust"]

[dependencies]
apt = ["libc6", "libgcc-s1"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "cd plrust/plrust && cargo pgrx install --features trusted -c /usr/bin/pg_config"
