[extension]
name = "index_advisor"
version = "0.2.0"
repository = "https://github.com/supabase/index_advisor"
license = "PostgreSQL"
description = "A PostgreSQL extension for recommending indexes to improve query performance."
documentation = "https://github.com/supabase/index_advisor"
categories = ["index_table_optimizations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C index_advisor install"
