[extension]
name = "mysql_fdw"
version = "1.2.0"
repository = "https://github.com/EnterpriseDB/mysql_fdw"
license = "Copyright"
description = "This PostgreSQL extension implements a Foreign Data Wrapper (FDW) for MySQL."
homepage = "https://www.enterprisedb.com/"
documentation = "https://github.com/EnterpriseDB/mysql_fdw"
categories = ["connectors"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C mysql_fdw install USE_PGXS=1"
