[extension]
name = "pgsql_ogr_fdw"
version = "1.1.5"
repository = "https://github.com/pramsey/pgsql-ogr-fdw"
license = "MIT"
description = "PostgreSQL foreign data wrapper for OGR."
documentation = "https://github.com/pramsey/pgsql-ogr-fdw"
categories = ["connectors"]

[dependencies]
apt = ["libgdal30", "libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pgsql-ogr-fdw install"
