[extension]
name = "pgtelemetry"
extension_name = "pgtelemetry"
version = "1.6.0"
repository = "https://github.com/adjust/pg-telemetry"
license = "PostgreSQL"
description = "Useful monitoring views for PostgreSQL. Monitors replication, disk usage, sources of concurrent queries and WAL throughput."
homepage = "https://github.com/adjust/pg-telemetry"
documentation = "https://github.com/adjust/pg-telemetry/blob/master/doc/pgtelemetry.html"
categories = ["tooling_admin", "metrics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install"
