[extension]
name = "hydra_columnar"
version = "1.1.2"
repository = "https://github.com/hydradatabase/hydra"
license = "GNU AGPL"
description = "Columnar storage for Postgres"
homepage = "https://www.hydra.so"
documentation = "https://github.com/hydradatabase/hydra"
categories = ["analytics"]

[dependencies]
apt = ["libc6", "libzstd1", "liblz4-1"]

[build]
postgres_version = "16"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C hydra/columnar install"
