[extension]
name = "pg_rational"
version = "0.0.2"
repository = "https://github.com/begriffs/pg_rational"
license = "MIT"
description = "Precise fractional arithmetic for PostgreSQL."
documentation = "https://github.com/begriffs/pg_rational"
categories = ["analytics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pg_rational install"
