[extension]
name = "system_stats"
version = "3.2.0"
repository = "https://github.com/EnterpriseDB/system_stats"
license = "Copyright"
description = "Expose system metrics such as CPU, memory and disk information."
documentation = "https://github.com/EnterpriseDB/system_stats"
categories = ["metrics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C system_stats install"
