[extension]
name = "kafka_fdw"
version = "0.0.3"
repository = "https://github.com/adjust/kafka_fdw"
license = "PostgreSQL"
description = "Kafka foreign database wrapper for postresql."
homepage = "https://www.adjust.com/"
documentation = "https://github.com/adjust/kafka_fdw"
categories = ["connectors"]

[dependencies]
apt = ["librdkafka1", "libc6"]

[build]
postgres_version = "16"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C kafka_fdw install"
