[extension]
name = "pg_proctab"
version = "0.0.12"
repository = "https://gitlab.com/pg_proctab/pg_proctab"
license = "Copyright"
description = "Access operating system process table."
homepage = "https://pg_proctab.gitlab.io/"
documentation = "https://gitlab.com/pg_proctab/pg_proctab"
categories = ["metrics"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make install USE_PGXS=1"
